name: Deploy PR previews

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency: preview-${{ github.ref }}

permissions:
  contents: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        if: github.event.action != 'closed'
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        if: github.event.action != 'closed'
        run: |
          npm ci
          npm run build
        env:
          CI: ""

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
